version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: beauty
      POSTGRES_DB: beauty_saas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://beauty:beauty@db:5432/beauty_saas
      JWT_SECRET: changeme
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: ["node", "dist/index.js"]
volumes:
  pgdata:
