name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint . --ext .ts
      - name: Format Check
        run: npx prettier --check .
      - name: Type Check
        run: npx tsc --noEmit
      - name: Run Tests
        run: npx jest --runInBand --detectOpenHandles --verbose
