name: Frontend CI

on:
  push:
    paths:
      - 'bsaas-front/**'
  pull_request:
    paths:
      - 'bsaas-front/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bsaas-front
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx ng lint
      - name: Run unit tests
        run: npx ng test --watch=false --browsers=ChromeHeadless
      - name: Build
        run: npx ng build --configuration production
